#!/bin/sh
sh $HOME/.config/polybar/launch.sh &
feh --bg-scale $HOME/Pictures/wallpapers/darker_unicat.png &

# Java bullshit (some programs break if you don't set this)
export _JAVA_AWT_WM_NONREPARENTING=1

# VMWare bullshit (keep this for copy/paste functionality)
vmware-user-suid-wrapper

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#313244"
bspc config focused_border_color "#cba6f7"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
